name: Release please

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dryRun:
        default: false
        type: boolean

jobs:
  release-please:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Install release-please
        run: npm install --global release-please@13.14.0
      
      - name: Run release-please
        shell: pwsh
        run: |
          $DryRunArg = ""  
        
          Write-Host "inputs.dryRun value = ${{ github.event.inputs.dryRun }}"

          if (-Not [string]::IsNullOrWhiteSpace("${{ github.event.inputs.dryRun }}"))
          {
            Write-Host "Executing a dry run"
            $DryRunArg = "--dry-run"
          }
        
          Write-Host "DryRunArg = $DryRunArg"

          release-please --debug release-pr --token="${{ github.token }}" --repo-url="CBenoit/actions-tests" "$DryRunArg"

